version: "3.7"

services: 
  #frontend:
  #  build: 
  #    context: ./frontend
  #  volumes:
  #    - ./frontend:/var/www/html
  #  ports:
  #    - "80:80"
  #    - "443:443"
  app:
    build: 
      context: ./app
    ports: 
      - "8000:8000"
    volumes: 
      #- ./app:/app
      - data:/staticfiles
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    
  proxy:
    depends_on: 
      - app
    build: 
      context: ./proxy
    volumes:
      - data:/staticfiles
      - ./certtificates:/etc/letsencrypt/live/generatedcert/
    ports:
      - "80:80"
      - "443:443"
    environment: 
      # - CERTBOT_MODE=STAGING
      - CERTBOT_MODE=PROD

volumes: 
  data:
